name: 'Build and Publish Docker Image to GitHub Packages Registry'
description: 'GitHub Action to build and publish Docker Images to GitHub Registry.'
inputs:
  github-token:
    description: 'GitHub token to push Docker image to GitHub Packages'
    required: true
  image-name:
    description: 'Docker Image name'
    required: true
  image-tag:
    description: 'Docker Image tag'
    default: "latest"
    required: false
  extract-git-tag:
    description: 'Extract git-tag from repository'
    default: "false"
    required: false
  dockerfile:
    description: 'Dockerfile name'
    default: "Dockerfile"
    required: false
  build-context:
    description: 'Path to build context'
    default: "."
    required: false
  pull-image:
    description: 'Pull the image before buiding it'
    default: "false"
    required: false
  build-args:
    description: 'Any build arguments'
    default: ""
    required: false
  build-only:
    description: 'Just build the image without pushing it to registry'
    default: "false"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.image-name }}
    - ${{ inputs.image-tag }}
    - ${{ inputs.extract-git-tag }}
    - ${{ inputs.dockerfile }}
    - ${{ inputs.build-context }}
    - ${{ inputs.pull-image }}
    - ${{ inputs.build-args }}
    - ${{ inputs.build-only }}
branding:
  icon: 'box'
  color: 'blue'
